version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: weather_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-weather_db}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  weather_pipeline:
    build: .
    container_name: weather_app_container
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - TARGET_CITY=${TARGET_CITY}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-weather_db}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-password}
    depends_on:
      - db

volumes:
  pgdata: